# Generated by Django 5.2.5 on 2025-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
